function B_e = beamForce(b_e,x_ac_e,x_sc)
%beamForce
%    B_e = beamForce(B_E,X_AC_E,X_SC)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    14-Nov-2025 15:13:04

t2 = b_e.^2;
t3 = -x_sc;
t4 = b_e./2.0;
t5 = t3+x_ac_e;
t6 = t2./1.2e+1;
t8 = b_e.*t5.*(-1.0./2.0);
B_e = [t4;t6;t8;t4;-t6;t8];
end
