function S_e = plateForce(a_e,b_e)
%plateForce
%    S_e = plateForce(A_E,B_E)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    24-Dec-2025 11:51:34

t2 = a_e.*b_e;
t5 = (b_e.*t2)./3.0;
t6 = (a_e.*t2)./3.0;
t7 = -t5;
t8 = -t6;
S_e = [t2;t5;t8;t2;t5;t6;t2;t7;t6;t2;t7;t8];
end
