function M_e = beamMass(b_e,mu_e,I_sc_e,x_cm_e,x_sc)
%beamMass
%    M_e = beamMass(B_E,MU_E,I_sc_e,X_CM_E,X_SC)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    14-Nov-2025 15:13:04

t2 = b_e.^2;
t3 = b_e.^3;
t4 = -x_sc;
t5 = (I_sc_e.*b_e)./3.0;
t6 = (I_sc_e.*b_e)./6.0;
t8 = b_e.*mu_e.*(1.3e+1./3.5e+1);
t9 = b_e.*mu_e.*(9.0./7.0e+1);
t7 = t4+x_cm_e;
t10 = (mu_e.*t3)./1.05e+2;
t11 = (mu_e.*t3)./1.4e+2;
t13 = mu_e.*t2.*(1.1e+1./2.1e+2);
t14 = mu_e.*t2.*(1.3e+1./4.2e+2);
t12 = -t11;
t15 = -t13;
t16 = -t14;
t17 = b_e.*mu_e.*t7.*(3.0./2.0e+1);
t18 = b_e.*mu_e.*t7.*(7.0./2.0e+1);
t21 = (mu_e.*t2.*t7)./2.0e+1;
t22 = (mu_e.*t2.*t7)./3.0e+1;
t19 = -t17;
t20 = -t18;
t23 = -t21;
t24 = -t22;
M_e = reshape([t8,t13,t20,t9,t16,t19,t13,t10,t23,t14,t12,t24,t20,t23,t5,t19,t22,t6,t9,t14,t19,t8,t15,t20,t16,t12,t22,t15,t10,t21,t19,t24,t6,t20,t21,t5],[6,6]);
end
