function K_e = beamStiffness(b_e,E_e,I_e,G_e,J_e)
%beamStiffness
%    K_e = beamStiffness(B_E,E_e,I_e,G_e,J_e)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    14-Nov-2025 15:13:04

t2 = 1.0./b_e;
t3 = t2.^2;
t4 = t2.^3;
t5 = G_e.*J_e.*t2;
t6 = E_e.*I_e.*t2.*2.0;
t7 = E_e.*I_e.*t2.*4.0;
t8 = E_e.*I_e.*t3.*6.0;
t10 = E_e.*I_e.*t4.*1.2e+1;
t11 = -t5;
t9 = -t8;
t12 = -t10;
K_e = reshape([t10,t8,0.0,t12,t8,0.0,t8,t7,0.0,t9,t6,0.0,0.0,0.0,t5,0.0,0.0,t11,t12,t9,0.0,t10,t9,0.0,t8,t6,0.0,t9,t7,0.0,0.0,0.0,t11,0.0,0.0,t5],[6,6]);
end
